### PR TITLE
Looking for a quality review for documentation on some Shell methods

### PR DESCRIPTION
**Pull request by carols10cents**
I'll be ok making the patch, just wanted to get another set of eyes on these :D

### CODE REVIEW

**Comment by semmons99** [comment]
Awesome work!

**Comment by practicingruby** [comment]
+1, Looks good to me.

**Comment by phiggins** [comment]
:+1:

**Comment by carols10cents** [comment]
Thanks for the review everyone! I've submitted my patch in redmine. Yay docweek! :heart: :heart: :heart:

**Pull request closed without merging**
