### PR TITLE
Documentation for Hash

### PR DESCRIPTION
**Pull request by xenda**
Adds some top level documentation on Hash, and some ideas on how it's often used. Would like some feedback on where to go from here/what to fix to prepare it as a patch.

### CODE REVIEW

**Comment by semmons99** [comment]
Do you need help getting this patch created for submission to ruby-core?

**Comment by xenda** [comment]
If you think it could qualify as that, I'd give it a try. I've already experimented with using the git format-patch and see it creates a patch for each commit. Since I'm using several commits here, not sure what my strategy would be. I was thinking on collapsing all the commits on one and then create the patch.

**Comment by semmons99** [comment]
Yeah. Rebase your commits into a single commit and then use `git format-patch HEAD~1`.

**Comment by xenda** [comment]
Thanks for your help clarifying that. Just did it and sent a ticket: http://redmine.ruby-lang.org/issues/5405. Let's hope for the best now :). Will try to do a couple more today.

**Pull request closed without merging**
