### PR TITLE
Add documentation for rinda

### PR DESCRIPTION
**Pull request by Nerian**
Documenting lib/rinda/*

### CODE REVIEW

**Comment by phiggins** [comment]
Great work! I left some comments inline.

**Comment by Nerian** [comment]
@phiggins

Thanks for the feedback!

The next step would be submitting a patch, is it ready for that?

**Comment by phiggins** [comment]
I think it's ready, but hopefully we can get at least one more person to read it over (_hint, hint_).

**Comment by steveklabnik** [comment]
Reading.

**Pull request merged**
